
services:
  node-cache-app:
    image: node:18.15.0-bullseye-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_cache
    ports:
     - 4000:4000
    expose:
      - 4000
    depends_on:
      - redis_service
    networks:
      - internal
  

  cache_service:
    image: redis:7.0-alpine
    container_name: redis_service
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - internal


networks:
  internal:
    driver: bridge
    